apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-slave
    labels:
        app: redis
spec:
    selector:
        matchLabels:
            app: redis
            role: slave
            tiler: backend
    replicas: 2
    template:
        metadata:
            labels:
                app: redis
                role: slave
                tiler: backend
        spec:
            containers:
            - name: slave
              image: gcr.io/google_samples/gb-redisslave:v3
              resources:
                requests:
                    cpu: 100m
                    memory: 100Mi
              env:
              - name: GET_HOSTS_FROM
                value: dns