apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    selector:
        matchLabels:
            app: wordpress
    replicas: 1
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: wordpress:4.8-apache
              env:
              - name: WORDPRESS_DB_HOST
                value: mysql
              - name: WORDPRESS_DB_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mysql
                        key: password
              ports:
              - containerPort: 80
              volumeMounts:
              - name: wordpress
                mountPath: /var/www/html
            volumes:
            - name: wordpress
              persistentVolumeClaim:
                claimName: wordpress

